## 端口号 上下文路径
server:
  port: 8989
  servlet:
    context-path: /crm
## 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  ## freemarker  控制源解析器
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
## mybatis 整合配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.mohen.crm.vo;com.mohen.crm.query;com.mohen.crm.dto
  configuration:
    map-underscore-to-camel-case: true
## pageHelper  分页插件
pagehelper:
  helper-dialect: mysql